sudo: required 
language: node_js
node_js:
    - "stable"
    
services: 
    - docker

before_install: 
    - docker build -t wilpat/Frontend-SE -f Dockerfile.dev .
script:     
    - docker run -e CI=true wilpat/Frontend-SE npm run test -- --coverage
